services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: slideshow-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/projects:/app/projects
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - slideshow-network
    restart: unless-stopped

networks:
  slideshow-network:
    driver: bridge

volumes:
  projects:
    driver: local